/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class model_SystemCredentialsManager */

#ifndef _Included_model_SystemCredentialsManager
#define _Included_model_SystemCredentialsManager

#ifdef EASYRUNDLL
#undef EASYRUNDLL
#endif // EASYRUNDLL

#ifdef EASYRUNDLL_EXPORTS
#define EASYRUNDLL __declspec(dllexport)
#else
#define EASYRUNDLL __declspec(dllimport)
#endif

#ifdef __cplusplus
extern "C" {
#endif

	EASYRUNDLL void CALLBACK ElevMain(HWND, HINSTANCE, LPTSTR, int);

	/*
	 * Class:     model_SystemCredentialsManager
	 * Method:    getCreds
	 * Signature: (Ljava/lang/String;Z)[Lmodel/SystemCredentialsManager/WindowsCredential;
	 */
	JNIEXPORT jobjectArray JNICALL Java_model_SystemCredentialsManager_getCreds(JNIEnv *, jclass, jstring, jboolean);

	/*
	 * Class:     model_SystemCredentialsManager
	 * Method:    getCred
	 * Signature: (Ljava/lang/String;I)Lmodel/SystemCredentialsManager/WindowsCredential;
	 */
	JNIEXPORT jobject JNICALL Java_model_SystemCredentialsManager_getCred(JNIEnv *, jclass, jstring, jint);

	/*
	 * Class:     model_SystemCredentialsManager
	 * Method:    newCred
	 * Signature: (Lmodel/SystemCredentialsManager/WindowsCredential;)I
	 */
	JNIEXPORT jint JNICALL Java_model_SystemCredentialsManager_newCred(JNIEnv *, jclass, jobject);

	/*
	 * Class:     model_SystemCredentialsManager
	 * Method:    updateCred
	 * Signature: (Lmodel/SystemCredentialsManager/WindowsCredential;)I
	 */
	JNIEXPORT jint JNICALL Java_model_SystemCredentialsManager_updateCred(JNIEnv *, jclass, jobject);

	/*
	 * Class:     model_SystemCredentialsManager
	 * Method:    deleteCred
	 * Signature: (Ljava/lang/String;I)I
	 */
	JNIEXPORT jint JNICALL Java_model_SystemCredentialsManager_deleteCred(JNIEnv *, jclass, jstring, jint);

	/*
	 * Class:     model_SystemCredentialsManager
	 * Method:    getErrMsg
	 * Signature: (I)Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_model_SystemCredentialsManager_getErrMsg(JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
